import type { NextPage } from 'next'
import { useFetch } from "use-http";
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const { error, data: dataset = '' } = useFetch('/5char.es.txt', {}, [])
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Reverse Wordle!
        </h1>
      </main>
    </div>
  )
}

export default Home
